# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productTB', '0002_auto_20171129_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
