# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productTB', '0003_auto_20171129_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image_url',
        ),
    ]
